# Funding options for COCO - The AI Design Companion
# This file enables the "Sponsor" button on GitHub

# GitHub Sponsors (primary)
github: miladyxx333-lab

# Patreon
patreon: coyotlcompany

# OpenSea SpotPunk NFTs
custom: 
  - "https://opensea.io/es/collection/spotpunk"
